name: Actualizar tabla de templates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # copiado supongo que necesario para fechas

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run script
        run: python .github/scripts/update_readme.py

      - name: Crear Pull Request del catálogo
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Actualizar catálogo de templates"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: "automation/update-template-catalog"
          base: main
          delete-branch: true
          title: "Actualizar catálogo de templates"
          body: |
            Actualiza automáticamente los catálogos generados desde los archivos `metadata.json`.
          add-paths: |
            README.md
            **/README.md
